spring.application.name=infrastructure

server.error.include-stacktrace=NEVER

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/sql

spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mariadb://localhost:3306/hydrotrack
spring.datasource.username=server
spring.datasource.password=server

messaging.nats.url=nats://localhost:4222