version: '3.8'

services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password   # change this
      MYSQL_DATABASE: hydrotrack          # optional
      MYSQL_USER: server                  # optional
      MYSQL_PASSWORD: server      # optional
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
