plugins {
    id 'java'
}

group = 'com.laurenci.hydrotrack'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":core")

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor

    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}